# Generated by Django 2.2.9 on 2020-01-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('old_rentail_price', models.FloatField()),
                ('old_sale_price', models.FloatField()),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
            ],
        ),
    ]
